### ISSUE TITLE
Keyboard and DualShock4 not working. I pressed the buttons to start the game but they don't work.

### ISSUE THREAD

**Issue by WCarpet97** [Rayduxz/DIVA-Loader#10]
I start the game, everything is normal... until I press the start button and nothing happens. I'm trying to fix it by myself... but at the momment; please help (also with my other issue).

**Comment by Rayduxz** [comment]
Please indicate your game version and make sure you are using the latest DIVA Loader version.

Also double check your settings are correct.
Check that "input_emulator" is set to true in "components.ini".
Check your keybinds at "keyconfig.ini".

**Comment by WCarpet97** [comment]
Ok, so the version of PDAFT is 7.10 and the latest DIVA Loader is 1.7 or 1.0 (1.01)?
I'll check the other stuff in a momment...

**Comment by WCarpet97** [comment]
I'll try 1.7 Hotfix 1

**Comment by WCarpet97** [comment]
I checked the stuff and it's correct... but it's still not working...

**Comment by WCarpet97** [comment]
The logos (SEGA, Crypton, NicoNico) flash so fast and then the op. begins. It keeps saying "Touch the screen". I clicked with the mouse, I pressed "Options" in my DS4, I pressed "Enter" in my keyboard... none worked :(

**Comment by WCarpet97** [comment]
Ok, I noticed something: 
![Screenshot_4](https://user-images.githubusercontent.com/47161673/59895126-f8d4df80-93a8-11e9-9e8e-c5ec24ac4256.png)
Touch Panel and Touch Slider are in NG when they should be in OK, right? How can I fix this? I checked my settings and I think they're ok...

**Comment by WCarpet97** [comment]
![image](https://user-images.githubusercontent.com/47161673/59895340-d7c0be80-93a9-11e9-9c24-71aeb7e5eea4.png)
Huh... weird...

**Comment by WCarpet97** [comment]
I think my "diva.exe" is somehow not reading the plugins....

**Comment by Rayduxz** [comment]
What Windows version are you on?
Where are you launching the game from? Directly from "diva.exe" or from a shortcut?
Also please show a screenshot of your root game folder, plugins folder and "config.ini" file.
Make sure you are using the original executable.

**Comment by Rayduxz** [comment]
Continue at https://github.com/Rayduxz/DIVA-Loader/issues/13#issuecomment-504297738
This is because your game is not loading plugins correctly.
