### ISSUE TITLE
Unicode compatibility

### ISSUE THREAD

**Issue by WCarpet97** [Rayduxz/DIVA-Loader#13]
Evidence:
   Fullscreen is in 0 but is still puts the game in Fullscreen.
   Input Touch Panel and Touch Slider are TRUE in .ini but when I start the game they are in NG 
    instead of OK.

It may be happening with the other settings but I can't really confirm it since I can't make it through the START screen...

Please help me solve this problem.

PDAFT Version 7.10
Version B Revision 3

My PC:
Intel Core i5 8400
GeForce GTX 1050 Ti 4GB
8 GB RAM

System Startup shown to me:
![Screenshot_4](https://user-images.githubusercontent.com/47161673/59895788-7ef22580-93ab-11e9-8864-1c58a5920866.png)

**Comment by WCarpet97** [comment]
Also, I'm in Windows 10 PRO

**Comment by WCarpet97** [comment]
I'm using DIVA Loader 1.7 Hotfix 1
I've tried the others and none worked for me...

**Comment by WCarpet97** [comment]
Oh, stupid me! I noticed that the game should not have the MDATA already inserted...

**Comment by WCarpet97** [comment]
I think that's the problem...

**Comment by Rayduxz** [comment]
Please show a screenshot of your root game folder, plugins folder and "config.ini" file.
Make sure you are using the original executable.

**Comment by WCarpet97** [comment]
The problem was the game location, it was in Users\MYUSER\Desktop (My user name has an accent). I moved it to C:\ProgramData and it worked there! Thanks! :)

**Comment by Rayduxz** [comment]
I will reopen this because this is an actual issue, the idea is to provide full Unicode compatibility.

**Comment by Rayduxz** [comment]
https://github.com/Rayduxz/DIVA-Loader/commit/57375413d9808307afb0284320c663d694349f28

Fixed thanks to somewhatlurker, folders can now contain Unicode characters.
