### ISSUE TITLE
Rename TLAC to DivaHook

### ISSUE THREAD

**Issue by SwigS-27** [Rayduxz/DIVA-Loader#28]
yeah that's it.

**Comment by Rayduxz** [comment]
Why?

**Comment by nastys** [comment]
Rename it to ControllerEmulator, if anything.

**Comment by SwigS-27** [comment]
And well it's not really TLAC is it?

**Comment by nastys** [comment]
But it is.

**Comment by SwigS-27** [comment]
unless it does more, it's just the DivaHook part right?

**Comment by nastys** [comment]
It's literally a fork of TLAC. It handles input emulation. You could even rename samyuu's TLAC DLL to TLAC.dva and it would probably work fine.

**Comment by somewhatlurker** [comment]
The issue here is that TLAC is used as the project name and DivaHook is a part of TLAC that was copied.

**Comment by SwigS-27** [comment]
Yeah, thanks for putting it into words better than I could

**Comment by somewhatlurker** [comment]
BUT...   ELAC had a DivaHook too, so DivaHook isn't necessarily the best name.

**Comment by nastys** [comment]
DivaInput?

**Comment by somewhatlurker** [comment]
it's more than just input

**Comment by SwigS-27** [comment]
^

**Comment by somewhatlurker** [comment]
more like DivaTrustUsYouNeedThis

**Comment by Rayduxz** [comment]
I would like to honor samyuu's original project and keep it as "TLAC" even if it's technically just the "DivaHook" part.

**Comment by nastys** [comment]
What's the "missing" part?

**Comment by Rayduxz** [comment]
The prepatch executable and the DLL injector.

**Comment by somewhatlurker** [comment]
Yeah, this has the main part of TLAC.
