### ISSUE TITLE
XINPUT1_4.dll is missing error on v1.4 

### ISSUE THREAD

**Issue by starduststarter** [Rayduxz/DIVA-Loader#4]
The v1.4 release gave me an error stating that XINPUT1_4.dll is missing. After proceeding, TLAC.dva failed to load.

This isn't present in v1.3.

**Comment by Rayduxz** [comment]
Try the to update your DirectX runtime.

https://www.microsoft.com/en-us/download/details.aspx?id=35

**Comment by starduststarter** [comment]
It's already on the latest version.
On Windows 7 x64

**Comment by Rayduxz** [comment]
Windows 7 is not supported yet.
Only Windows 8.1 and above.

**Comment by Rayduxz** [comment]
Windows 7 supported since v1.5 (dnsapi.dll)
https://github.com/Rayduxz/DIVA-Loader/commit/55fb22271a0627edafe2392fc2ab91950c31d334

No support for videos yet (Possibly related to WMVDECOD.DLL)
