### ISSUE TITLE
Both right and left triggers of xbox elite controller do not work

### ISSUE THREAD

**Issue by OliveInto** [Rayduxz/DIVA-Loader#5]
This is what I configed in keyconfig.ini
> JVS_START = Enter, Ds4_Options, XINPUT_START
JVS_TRIANGLE = W, I, Ds4_Triangle, Ds4_DPad_Up, XINPUT_Y, XINPUT_UP, XINPUT_LT
JVS_SQUARE = A, J, Ds4_Square, Ds4_DPad_Left, XINPUT_X, XINPUT_LEFT, XINPUT_LS
JVS_CROSS = S, K, Ds4_Cross, Ds4_DPad_Down, XINPUT_A, XINPUT_DOWN, XINPUT_RS
JVS_CIRCLE = D, L, Ds4_Circle, Ds4_DPad_Right, XINPUT_B, XINPUT_RIGHT, XINPUT_RT

It seems that only XINPUT_RS and XINPUT_LS work properly, when I press triggers the game dose not response.

**Comment by Rayduxz** [comment]
Is this still present on the latest version?
I don't have an Xbox One Elite Controller to test, just the normal one.

**Comment by OliveInto** [comment]
I tried the latest version, the problem solved, thank you very much!
