### ISSUE TITLE
Game not at Fullscreen (Only uses a part of the screen. Anything else: black). I've tried everything.

### ISSUE THREAD

**Issue by WCarpet97** [Rayduxz/DIVA-Loader#9]
I've used many releases but none of them work. I'll keep trying... But still, I need help. Please help.

**Comment by Rayduxz** [comment]
If "fullscreen = true" is not working for you...
Try the following in "config.ini",

`[Resolution]
# Set resolution and window size if windowed
Borderless =1
Fullscreen =0
Width =1920
Height =1080`

Set "Width" and "Height" to your desktop resolution.

**Comment by WCarpet97** [comment]
It's not working :(

**Comment by WCarpet97** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/47161673/59894801-962f1400-93a7-11e9-866a-74c626be26ce.png)

I did what you told me to do and it's still not working.

**Comment by Rayduxz** [comment]
Continue at https://github.com/Rayduxz/DIVA-Loader/issues/13#issuecomment-504297738
This is because your game is not loading a plugin correctly.
